### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by vilhai** [VSirvio/tsoha-keskustelusovellus#1]
Sovelluksen toiminnot toimivat  hyvin ja käyttäminen on helppoa ja intuitiivista jo nyt, vaikkei käyttöliittymää olekaan vielä graafisesti toteutettu.  Kaikki toimii sulavasti ja tekninen toteutus on laadukas. Koodi on siistiä ja se on jaoteltu hyvin eri moduuleihin ja funktioihin. Viestit ovat oma luokka, joka on myös toteutettu hyvin. Tietokannan rakenne on hyvä ja siinä on toteutettu hyvin viestien ja vastausten polveutuminen toisistaan.

Mahdotonta keksiä mitään vikaa. Toki sovellus on täysin vaiheessa, mutta kaikki toteutetut toiminnot toimivat todella hyvin ja koodi ja sovelluksen sekä tietokannan rakenne on hyvin selkeä.

**Comment by VSirvio** [comment]
Kiitos palautteesta!
