### ISSUE TITLE
Tsoha vertaisarviointi

### ISSUE THREAD

**Issue by Kissaniemi** [VSirvio/tsoha-keskustelusovellus#2]
Kiva että sovellusta pääsi testaamaan suoraan sivulta!

Koodi oli järkevästi jäsennelty ja nimetty, ja koska sovelluksen ulkonäkö oli vielä kesken, niin keskityn lähinnä sovelluksen käytettävyyden parantamiseen (nämä ovat kaikki vain ehdotuksia, kaikki luvatut ominaisuudet näyttäisi toimivan pitkälti kuten pitääkin).

Pienempi lisäys:
JavaScript-tarkastuksen lisäksi oli hyvä, että viestien pituus vielä tarkistettiin. Voisiko tähän vielä lisätä virheviestin, sen sijaan että sivu vain palaa takaisin ilman mitään ilmoitusta.

Kun viestiä alapeukuttaa, niin sen poistamiseksi pitää painaa “poista tykkäys” tekstiä, olisiko mahdollista saada jokin “poista vihaus” tyyppinen teksti tilalle? Ja kun tykkää/ei tykkää viestistä, sivun päivittyessä filteröinti palautuu “Uusimmat” tilaan, saisiko sen päivityksen jälkeen pysymään samana.

Isompi lisäys:
Viestien filteröintijärjestys toimii vähän hassusti, kun viestiketjuja voi olla useita saman keskustelun sisällä. Esim. Jos johonkin viestiin ketjutettu kommentti on tykätyin/vihatuin/uusin, filteröinti listaa aina alkuperäisen viestin ensin. Tämän muuttaminen vaatisi varmaan ketjuttamisen “poiston” niin että viestit saisi filteröityä näkymään ilman ketjutusta.

**Comment by VSirvio** [comment]
Kiitos hyödyllisestä palautteesta! Toteutin kaiken muun paitsi viimeisen kohdan filteröintijärjestyksestä. Olen jäljitellyt siinä tarkoituksella Redditin toimintatapaa, jossa vain ylimmän tason viestit lajitellaan annetun lajitteluperusteen mukaan ja viestien puurakenne säilytetään.
